- README.md
- package-lock.json
- package.json
- rollup.config.js
- src/App.svelte
- src/data/chapterNavs.js
- src/index.html
- src/routes/About.svelte
- src/routes/Acknowledgements.svelte
- src/routes/Overview.svelte
Changes:
* Adding the npm package https://www.npmjs.com/package/@openacr/openacr
* Renamed openacr references.
* Add rollup-yaml package to load YAML files from openacr.
* Tested changing the navigation to match the openacr chapters. Note: the chapter navigation doesn't work.
* Updated the pages to have some OpenACR initial text.
You can see the changes live on https://gsa.github.io/openacr-editor/
> Add openacr package and minor changes to get going on modifying the app

- src/components/YourReport.svelte
- src/components/report/ReportHTMLDownload.svelte
- src/components/report/ReportYAMLDownload.svelte
- src/routes/About.svelte
- src/routes/Report.svelte
- src/stores/evaluation.js
- src/utils/createCleanEvaluation.js
Changes:
* Started to add metadata fields from OpenACR to the storage JSON structure.
* Adjusted the report page to add/edit the metadata fields.
* Added 'Download report (YAML)' button on the report page.
* Started adding product names to some of the different pages.
You can see the changes live on https://gsa.github.io/openacr-editor/
> Added OpenACR meta structure and YAML download.

- src/components/YourReport.svelte
- src/components/report/ReportMarkdownDownload.svelte
- src/components/report/ReportSummary.svelte
- src/stores/evaluation.js
- src/utils/createCleanEvaluation.js
- src/utils/importEvaluation.js
Closes https://github.com/GSA/openacr/issues/192
QA steps:
3. Click 'Open report'.
4. Upload a yaml file from OpenACR. Try the 'drupal-9.yaml' or any of the yaml files from https://github.com/GSA/openacr/tree/main/openacr.
5. Switch to the 'About' page.
6. Confirm you see the values in the fields from the yaml file.
7. Click the 'View report' or 'Report' tab.
8. Confirm you see a 'Valid' message.
9. Confirm the HTML on the page displays the various sections except tables, chapters, related OpenACRs matching the YAML file.
10. Click the 'Download Report (HTML)' and confirm the HTML file downloaded matches the page.
11. Click the 'Download Report …
> Adjusted import new report to handle OpenACR yaml files

- src/App.svelte
- src/components/Chapter.svelte
- src/components/Component.svelte
- src/components/Criteria.svelte
- src/components/YourReport.svelte
- src/components/YourReportProgress.svelte
- src/components/report/ReportHTMLDownload.svelte
- src/components/report/ReportMarkdownDownload.svelte
- src/components/report/ReportNumbers.svelte
- src/components/report/ReportValid.svelte
- src/components/report/ReportYAMLDownload.svelte
- src/routes/Report.svelte
- src/stores/evaluation.js
- src/utils/createCleanEvaluation.js
- src/utils/getEvaluatedItems.js
- src/utils/importEvaluation.js
- src/utils/validate.js
Closes https://github.com/GSA/openacr/issues/207
QA steps:
**New report**
3. Switch to the different table/chapter pages.
4. Confirm you see form fields for chapter notes.
5. Confirm you see many criteria.
6. Confirm for A/AA/AAA you see multiple components with fields for level and notes.
7. Confirm for FPC, Hardware, Software, Docs you see only one field for level and notes.
8. Adjust the level and add some notes.
9. Click the 'View report' or 'Report' tab.
10. Confirm you see a 'Valid' message.
11. Click the 'Download Report (YAML)' and confirm the YAML file has the various chapters, criteria, and components filled out.
**Existing report** …
> OpenACR chapter forms

- src/routes/Overview.svelte
@danid123 & @dmundra let me know what you think of the text here. I'm not sure if my link in the overview to start a new report will actually work. Still experimenting here. Brought over some language from the /gsa/openacr project description.
> Proposed changes for the Overview

- package-lock.json
- package.json
- src/components/report/ReportHTMLDownload.svelte
- src/components/report/ReportLicense.svelte
- src/routes/About.svelte
- src/routes/Report.svelte
- src/utils/createCleanEvaluation.js
- src/utils/honourFragmentIdLinks.js
- src/utils/importEvaluation.js
- src/utils/license.js
Closes https://github.com/GSA/openacr/issues/224
**New report QA**
3. Switch to the About page.
4. Confirm you see the license field populated to CC-BY-4.0.
5. Click on the field and search for other licenses by typing or scrolling.
6. Confirm the search works and finds matching licenses.
7. Adjust the license and add some notes.
8. Click the 'View report' or 'Report' tab.
9. Confirm you see a 'Valid' message.
10. Confirm the HTML on the page displays the license selected (all the way to the bottom of the page).
**Existing report QA**
2. Click …
> License field dropdown

- src/components/AddOther.svelte
- src/components/Related.svelte
- src/components/report/ReportSummary.svelte
- src/data/helpText.yaml
- src/routes/About.svelte
- src/utils/createCleanEvaluation.js
- src/utils/importEvaluation.js
Closes https://github.com/GSA/openacr/issues/220
**New report**
3. Switch to the about page.
4. Confirm you see a section at the bottom for 'Related OpenACRs'.
5. Click the button 'Add related OpenACR'.
6. Confirm you are given a pair of fields, one text field for 'URL' and one dropdown for 'Type'.
7. Click the add button again to create additional pair of fields.
8. Click the trash icon to remove a pair of fields.
9. Confirm the pair is deleted.
10. In the pairs, add URLs and set the type to primary or secondary.
11. Click the 'View report' or 'Report' tab.
12. Confirm you see a 'Valid' message.
13. Confirm in the report you see the 'Related …
> Related OpenACRs

- src/routes/Glossary.svelte
Page: https://gsa.github.io/openacr-editor/glossary
Closes https://github.com/GSA/openacr/issues/239
> Initial commit of accessibility glossary

- .github/workflows/a11y.yaml
From https://docs.npmjs.com/cli/v8/commands/npm-ci
> Switched npm install to npm ci for a11y GitHub action

- package-lock.json
- src/App.svelte
- src/components/Chapter.svelte
- src/components/Criteria.svelte
- src/index.html
- src/routes/About.svelte
- src/routes/Acknowledgements.svelte
- src/routes/Glossary.svelte
- src/routes/Overview.svelte
- src/routes/Report.svelte
- src/utils/honourFragmentIdLinks.js
Also added anchor headers to overview page.
Closes https://github.com/GSA/openacr/issues/244
**QA**
2. Visit the about, and table/chapters pages.
3. Confirm each section has a header and is collapsed.
4. Confirm you can expand and collapse all sections.
5. Confirm you can expand a section and change the values.
6. Confirm for the different headers appear with an anchor link.
7. Click the anchor link and confirm it works.
8. Click the 'View report' or 'Report' tab.
9. Confirm you see a 'Valid' message.
10. Confirm in the report you see the data correctly match the values you have set.
> Adjusted about page sections in details same for criteria.

- src/stores/evaluation.js
Fixes https://github.com/GSA/openacr/issues/256
Heavy handed solution but I should have done it when adding the related OpenACRs feature.
@danid123 let me know when you load this https://gsa.github.io/openacr-editor/ whether the error still persists.
> Incrementing data model to clear existing storages.

- .gitignore
- cypress/integration/import.test.js
- cypress/integration/report.test.js
- package-lock.json
Some additional cypress tests.
> Additional tests

- src/routes/Overview.svelte
https://github.com/GSA/openacr/issues/217
> Sentence case

- cypress/integration/chapter.test.js
- src/components/Component.svelte
Closes https://github.com/GSA/openacr/issues/243
Works exactly as requested. Give it a whirl!
> Char count

- cypress.json
- cypress/integration/accordion.test.js
- cypress/integration/report.test.js
- package-lock.json
- package.json
- src/components/report/ReportHTMLDownload.svelte
- src/components/report/ReportYAMLDownload.svelte
- src/components/report/ReportZipDownload.svelte
- src/routes/Report.svelte
- src/utils/createHTMLDownload.js
Working towards https://github.com/GSA/openacr/issues/259
**New report QA**
3. Switch to the different table/chapter pages.
4. Adjust some levels and add some notes.
5. Click the 'View report' or 'Report' tab.
6. Confirm you see a 'Valid' message.
7. Click the 'Download Report (YAML & HTML)' and confirm you are given a `.zip` file.
8. Unzip the file and confirm the HTML file downloaded matches the page.
9. Confirm the unzipped folder also has a YAML file that is valid.
**Existing report QA**
3. Click …
> Download zip

- README.md
- src/index.html
Closes https://github.com/GSA/openacr/issues/221
Open 'Terms' section on home page and view glossary page. Confirm styling is changed to match requirement in the issue.
> Added dd margin styling.

- cypress/integration/report.test.js
- src/components/report/ReportYAMLDownload.svelte
- src/components/report/ReportZipDownload.svelte
- src/routes/Report.svelte
Closes https://github.com/GSA/openacr/issues/279
**QA**
2. Click 'Open report'.
3. Upload a yaml file from OpenACR. Try the 'drupal-9.yaml' or any of the yaml files from https://github.com/GSA/openacr/tree/main/openacr.
4. Click the 'View report' or 'Report' tab.
5. Review the download button and text below it.
> Added download help text.

- cypress/integration/import.test.js
- cypress/integration/report.test.js
- public/images/check_circle.svg
- public/images/error.svg
- src/components/report/ReportValid.svelte
- src/routes/About.svelte
- src/routes/Report.svelte
Closes https://github.com/GSA/openacr/issues/299
Copied over USWDS alert styles and icons for our valid/invalid message.
**QA new report**
3. Navigate the sections and add fill in some fields.
4. Click the 'View report' or 'Report' tab.
5. Confirm you see a green 'Valid Report' box at the top of the report page with the message 'Your report has passed validation'.
6. Switch back to the 'About' page.
7. Under 'License' search for and select 'Invalid License'.
8. Click the 'View report' or 'Report' tab.
9. Confirm you see a red 'Error' box at the top of the report page with the message "Invalid: license 'Invalid' is not a recognized SPDX license …
> Customized validation to match USWDS alert style.

- README.md
ATAG is less well understood, and in some ways there is more commonality with WCAG-EM
> Wanted to mention WCAG-EM too

- cypress/fixtures/drupal-9.yaml
- cypress/integration/import.test.js
- cypress/integration/report.test.js
- package-lock.json
- package.json
- src/components/report/ReportHeader.svelte
- src/data/helpText.yaml
- src/routes/About.svelte
- src/stores/evaluation.js
- src/utils/createCleanEvaluation.js
- src/utils/importEvaluation.js
- src/utils/reportFilename.js
Closes https://github.com/GSA/openacr/issues/269
Summary of changes:
* Added last_modified_date and version to JSON structure where last_modified_date is set to today's date whenever a change is made and version is incremented whenever you load a file otherwise it starts from '1'.
* Add readonly fields to about page to view those values.
* Adjusted the report page to show the various dates in a list.
* Updated and added test assertions for the new fields.
**QA new report**
3. Navigate to the About page and add fill in some fields.
4. Confirm the 'Last Modified Date' is set to today's date and version is set to 1.
5. Click the 'View report' or …
> Last modified date and openacr version name

- src/utils/getCatalogs.js
@danid123 I think this will fix the bug you found. After deployment ('Deploy' action) is successful, can you open the site https://gsa.github.io/openacr-editor/ and let me know if you still get the error.
> Replaced null with default WCAG 2.0 508 catalog.

- src/data/helpText.yaml
> missed typo "anythng"

- src/index.html
> Revert "Prod"

- src/components/ExpandCollapseAll.svelte
- src/components/YourReport.svelte
- src/index.html
- src/routes/About.svelte
PO Approved
RITM1279126 
RITM1279034
> Uniform Button Styling

- src/components/report/ReportValid.svelte
> RITM1278621  fix 

- src/index.html
Changes to enable the DAP for open-acreditor
> DAP code added
